name: Medusa
description: Building blocks for digital commerce
instructions: null
changeLog:
  - date: 2023-03-24
    description: First Release
links:
  - label: Website
    url: https://medusajs.com/
  - label: Documentation
    url: https://docs.medusajs.com/
  - label: Github
    url: https://github.com/medusajs/medusa
  - label: Demo
    url: https://next.medusajs.com/
contributors:
  - name: Paco
    url: https://github.com/beakman
schema:
  type: object
  required:
    - projectName
    - medusaAdminUsername
    - medusaAdminPassword
  properties:
    # Project Config
    projectName:
      type: string
      title: Project Name
      default: medusa-store
    appServiceName:
      type: string
      title: App Service Name
      default: medusa
    databaseServiceName:
      type: string
      title: Database Service Name
      default: medusa-db
    redisServiceName:
      type: string
      title: Redis Service Name
      default: medusa-redis

    # Medusa Admin
    enableAdminPlugin:
      type: boolean
      title: Enable admin plugin
      default: true
    medusaAdminUsername:
      type: string
      title: Medusa Admin Username
    medusaAdminPassword:
      type: string
      title: Medusa Admin Password

    # Medusa Config
    jwtSecret:
      type: string
      title: JWT Secret
    cookieSecret:
      type: string
      title: Cookie Secret
    adminCors:
      type: string
      title: Admin CORS
      default: http://localhost:3000
    storefrontCors:
      type: string
      title: Storefront CORS
      default: https://example.com,http://localhost:8000,http://localhost:3000
    nodeEnv:
      type: string
      title: Node environment
      oneOf:
        - enum:
            - production
          title: Production
        - enum:
            - development
          title: Development
      default: production
    medusaPort:
      type: string
      title: Port
      default: "9000"

    # https://docs.medusajs.com/development/feature-flags/overview
    featureFlagProductCategories:
      type: boolean
      title: Enable product categories
      default: false
    featureFlagOrderEditing:
      type: boolean
      title: Enable order editing
      default: false
    featureFlagTaxInclusivePricing:
      type: boolean
      title: Enable tax inclusive pricing
      default: false
    featureFlagSaleChannels:
      type: boolean
      title: Enable sale channels
      default: false

    # Stripe Payments
    stripePluginEnabled:
      type: boolean
      title: Stripe enabled
      default: true
    stripeApiKey:
      type: string
      title: Stripe API key
      default: sk_test_...
    stripeWebhookSecret:
      type: string
      title: Stripe webhook secret
      default: whsec_...

    # MinIO File Storage
    # yarn add medusa-file-minio
    minioPluginEnabled:
      type: boolean
      title: MinIO enabled
      default: true
    minioServiceName:
      type: string
      title: MinIO Service Name
      default: medusa-storage
    minioServiceImage:
      type: string
      title: MinIO Service Image
      default: minio/minio:latest
    minioVolumeName:
      type: string
      title: MinIO volume name
      default: minio
    minioRootUser:
      type: string
      title: MinIO root user
      default: admin@example.com
    minioRootPassword:
      type: string
      title: MinIO root password
      default: supersecret

    # S3 File Storage
    # yarn add medusa-file-s3
    s3PluginEnabled:
      type: boolean
      title: S3 plugin enabled
      default: false

    # Meilisearch
    # yarn add medusa-plugin-meilisearch
    meiliPluginEnabled:
      type: boolean
      title: Meilisearch enabled
      default: true
    meiliServiceName:
      type: string
      title: Meilisearch Service Name
      default: medusa-search
    meiliServiceImage:
      type: string
      title: Meilisearch Service Image
      default: getmeili/meilisearch:v1.2.0
    meiliVolumeName:
      type: string
      title: Meilisearch Database Volume Name
      default: meilisearch
    meiliEnv:
      type: string
      title: Meilisearch environment
      oneOf:
        - enum:
            - production
          title: Production
        - enum:
            - development
          title: Development
      default: production
    meiliMasterKey:
      type: string
      title: Meilisearch master key

    # Notifications: SendGrid
    # yarn add medusa-plugin-sendgrid
    sendgridPluginEnabled:
      type: boolean
      title: SendGrid plugin enabled
      default: false
    sendGridApiKey:
      type: string
      title: SendGrid api_key
      default: SG.SECRET...
    sendGridFrom:
      type: string
      title: From email
